# Configura a URL base do servidor Ollama. pelo windows
quarkus.langchain4j.ollama.base-url=http://localhost:11434/
# Configura a URL base do servidor Ollama. via WSL
#quarkus.langchain4j.ollama.base-url=http://172.27.144.1:11434


# Define o ID do modelo que o Langchain4j irá invocar no Ollama.
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b

# Define um timeout para a chamada.
# Se o modelo demorar mais de 60s para responder, a chamada falhará.
quarkus.langchain4j.ollama.timeout=300s

# -- Config do Embedding Model
quarkus.langchain4j.ollama.embedding.model.model-id=nomic-embed-text

# -- Config do PgVector
# A dimensão do vetor deve ser a mesma do modelo de embedding utilizado. O Modelo 'nomic-embed-text' tem dimensão 768.
quarkus.langchain4j.pgvector.register-vector-pg-extension=true
quarkus.langchain4j.pgvector.dimension=768
quarkus.langchain4j.pgvector.table=travel_embeddings
quarkus.langchain4j.pgvector.drop-table-first=true

# Loga a request completa enviada ao LLM (incluindo o manifesto Tools)
quarkus.langchain4j.log-requests=true

#Loga a resposta completa recebida do LLM (Incluindo a chamada Tool)
quarkus.langchain4j.log-responses=true

# Formata a saida de log para JSON
quarkus.log.console.json=true
quarkus.log.console.json.pretty-print=true
